apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-ticket-service
  template:
    metadata:
      labels:
        app: booking-ticket-service
    spec:
      containers:
        - name: booking-ticket-service
          image: sangy1995/evento-master-booking-ticket-service:v1

          ports:
            - containerPort: 8085
          # Add other container configuration, environment variables, etc. as needed
---
apiVersion: v1
kind: Service
metadata:
  name: booking-ticket-service
spec:
  selector:
    app: booking-ticket-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: NodePort    
  # Add other service configuration as needed

