apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoservice
  template:
    metadata:
      labels:
        app: mongoservice
    spec:
      containers:
        - name: mongo-container
          image: sangy1995/mongo:v1

          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice-service
spec:
  type: NodePort
  selector:
    app: mongoservice
  ports:
    - name: mongoservice-port
      port: 27017
      targetPort: 27017


