apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-notification-service
  template:
    metadata:
      labels:
        app: email-notification-service
    spec:
      containers:
        - name: email-notification-service
          image: sangy1995/evento-master-email-notification-service:v1

          ports:
            - containerPort: 8099
          # Add other container configuration, environment variables, etc. as needed
---
apiVersion: v1
kind: Service
metadata:
  name: email-notification-service
spec:
  selector:
    app: email-notification-service
  ports:
    - name: http
      port: 8099
      targetPort: 8099
  type: NodePort    
  # Add other service configuration as needed

