apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserverdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: sangy1995/evento-master-eureka-server:v1

          ports:
            - containerPort: 8671
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  ports:
    - name: eureka-server
      port: 8671
      targetPort: 8671
  type: NodePort    
   

