apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: sangy1995/evento-master-payment-service:v1

          ports:
            - containerPort: 8088
          # Add other container configuration, environment variables, etc. as needed
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  type: NodePort
  # Add other service configuration as needed

