apiVersion: apps/v1
kind: Deployment
metadata:
  name: productwebappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-webapp
  template:
    metadata:
      labels:
        app: product-webapp
    spec:
      containers:
        - name: product-webapp
          image: sangy1995/product-webapp:v1

          ports:
            - containerPort: 4200
---

apiVersion: v1
kind: Service
metadata:
  name: product-webapp-service
spec:
  selector:
    app: product-webapp
  ports:
    - name: product-webapp
      port: 4200
      targetPort: 4200

