apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
        - name: registration-service
          image: sangy1995/evento-master-registration-service:v1

          ports:
            - containerPort: 8086
          # Add other container configuration, environment variables, etc. as needed
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: NodePort    
  # Add other service configuration as needed

